### ISSUE TITLE
Release a mpicbg with updated jama dependency

### ISSUE THREAD

**Issue by hinerm** [axtimwalde/mpicbg#11]
The 0.6.1 mpicbg has a `jama:jama` dependency, which has been replaced with `gov.nist.math:jama`. A release with the updated jama dependency would be nice so that it does not clash with the `imglib2-algorithm` jama dependency.

This should probably happen after switching to a parent pom-fiji that inherits from [pom-scijava 5.0+](https://github.com/scijava/pom-scijava/blob/80e542ae0ae909cc411599fb1501c7565840e232/pom.xml#L210), which manages a `jama.version`.

**Comment by axtimwalde** [comment]
Fixed with newer release.
