### ISSUE TITLE
Return transformation models for reusing

### ISSUE THREAD

**Issue by lacan** [axtimwalde/mpicbg#21]
In the case of matrix based models, it would be useful to have a way to get these back and to reapply them, through macros for example.

**Comment by axtimwalde** [comment]
@lacan, you can.  All matrix based models implement the corresponding interfaces

https://github.com/axtimwalde/mpicbg/blob/master/mpicbg/src/main/java/mpicbg/models/Affine1D.java

https://github.com/axtimwalde/mpicbg/blob/master/mpicbg/src/main/java/mpicbg/models/Affine2D.java

https://github.com/axtimwalde/mpicbg/blob/master/mpicbg/src/main/java/mpicbg/models/Affine3D.java

Or do you mean something else?

**Comment by lacan** [comment]
Hi@axtimwalde, what i was hoping for was to get a return value from the Interactive Affine plugin you made. I could also just reimplement that class just for my needs, but a toString() once the Enter key is pressed. Ideally I guess I should add something to InteractiveInvertibleCoordinateTransform so that on the enter keypress the ij.log outputs the matrix used for the transform but i am afraid that this would break the generic functionality of that class.

**Comment by axtimwalde** [comment]
@lacan thanks, that wasn't clear from the initial issue message.  Have you had a look at [TrakEM2](http://fiji.sc/TrakEM2) and the package [mpicbg-trakem2](https://github.com/trakem2/TrakEM2/tree/master/mpicbg-trakem2)? The aim of this package is to enable import and export of mpicbg transformations, used for XML import and export in [TrakEM2](http://fiji.sc/TrakEM2), [RVS](http://fiji.sc/Register_Virtual_Stack_Slices), and [TVS](http://fiji.sc/Transform_Virtual_Stack_Slices).  The `Interactive*` classes are just for testing, adding an empty abstract `onReturn()` method could do the job (affine and rigid could override this).  Feel free to hack it, I am happy to accept reasonable pull requests.  BTW, for the macro world, the [Landmark Correspondences](http://fiji.sc/Landmark_Correspondences) plugin in combination with ImageJ's ROI manager could be interesting.

**Comment by lacan** [comment]
Hi again. I will have a look at the TrakEM2 package for further inspiration. 
I am currently using the Landmarks Correspondences (have to file a small bug there) but again it is missing the fine tuning you can get with the interactive approaches. 
I'll send a pull request once I've added an overwritable onReturn method to the interactive classes and tested it on the linear transform methods. Thanks for your time!

**Comment by axtimwalde** [comment]
Resolved with https://github.com/axtimwalde/mpicbg/commit/32d22f30538946c5103da568f16b34d9badaa11f Thanks for the pull request.
