### ISSUE TITLE
Transformation output

### ISSUE THREAD

**Issue by a-jacobo** [axtimwalde/mpicbg#31]
Hi,

 Is there a way to output, perhaps to a text file, the homography matrix obtained from the aligned algorithm? I'm very happy with the results of the alignment but I would need to apply the same alignment to a set of manual traces that I've made over the images and for that I need the matrix.

Thanks,
Adrian.

**Comment by axtimwalde** [comment]
@a-jacobo from which alignment algorithm?

**Comment by a-jacobo** [comment]
Hi,

 Sorry, I meant of the SIFT alignment algorithm. I later realized that in Fiji you can first run the SIFT algorithm and get the transformation matrices printed to the log. That did the trick.

Thanks!
Adrian
