### ISSUE TITLE
Incorrect Kernel?

### ISSUE THREAD

**Issue by JonathanCSmith** [axtimwalde/mpicbg#37]
I can't see a good reason for the following line (and the one above it) to be using the horizontal kernel, I believe it should be using the vertical instead

https://github.com/axtimwalde/mpicbg/blob/050bc9110a186394ea15190fd326b3e32829e018/mpicbg/src/main/java/mpicbg/ij/util/Filter.java#L307

I believe the lines should be: 

					valb += v[ yk ] * tempData[ yb[ y + yk ] + x ];
					vala += v[ yk ] * tempData[ ya[ y + yk ] + x ];

**Comment by axtimwalde** [comment]
This is probably right.  But the method is not used---or is it?

**Comment by JonathanCSmith** [comment]
It is used for SIFT feature extraction. Specifically:

https://github.com/axtimwalde/mpicbg/blob/050bc9110a186394ea15190fd326b3e32829e018/mpicbg/src/main/java/mpicbg/ij/SIFT.java#L104

https://github.com/axtimwalde/mpicbg/blob/050bc9110a186394ea15190fd326b3e32829e018/mpicbg/src/main/java/mpicbg/imagefeatures/FloatArray2DScaleOctave.java#L219

and 

https://github.com/axtimwalde/mpicbg/blob/050bc9110a186394ea15190fd326b3e32829e018/mpicbg/src/main/java/mpicbg/imagefeatures/FloatArray2DScaleOctave.java#L243

The SIFT algorithm is used by the register virtual stack slices plugin https://github.com/fiji/register_virtual_stack_slices

**Comment by axtimwalde** [comment]
You are right.  But in all these places the h and v kernels are always
identical.  Would be good to fix though.  Could you do it and may be
write a unit-test?  Then file a pull request and I accept?

Thanks,
Stephan
