### ISSUE TITLE
Question about SIFT realization

### ISSUE THREAD

**Issue by Bleach665** [axtimwalde/mpicbg#54]
Hi. First of all thank you, your plugin works great. Much better than SIFT feature detection -> bruteforce descriptor matching from OpenCV. Are you using a special implementation of SIFT or this great result is consequence  of additional procedures?

**Comment by bogovicj** [comment]
@Bleach665 
The [image.sc forum](https://forum.image.sc/) is a more convenient place for discussions like this,
in part because more people can see/interact with it.  Please consider making a post there.

**Comment by Bleach665** [comment]
@bogovicj 
Ok, thanks.
